### ISSUE TITLE
Google Webfonts @import

### ISSUE THREAD

**Issue by smdnetau** [flipzoom/ProcessWire-AIOM-All-In-One-Minify#3]
Hi David,

This is a great module but I have a small issue when using it. Iif I link to a Google webfont in my CSS (via @import) it doesn't display at all.

Regards
Marty

**Comment by flipzoom** [comment]
Hi Marty, can you give me a code snippet? I'll be looking there as quickly as possible.

**Comment by smdnetau** [comment]
Hi David,

Sure thing. With my CSS I'm using LESS with Codekit to compile the CSS
(regular, not compressed).

CSS (my first few lines):

@import url(
http://fonts.googleapis.com/css?family=Merriweather:400,400italic,700,700italic|Merriweather+Sans:700,700italic,300italic,300|Oswald
);

*, *:after, *:before {
-webkit-box-sizing: border-box;
-moz-box-sizing: border-box;
 box-sizing: border-box;
}

.clear:after {
    content:"";
    display:table;
    clear:both;
}

Hope it helps.

**Comment by flipzoom** [comment]
Hi Marty, 

unfortunately I can not reproduce your issue. For me, the Google web fonts work with your code snippet. Nevertheless, I've fixed a number of problems with the minimization library. I have replaced them with our own development in the current dev branch. Please test version 2.1 from the dev branch and let me know whether the issue is resolved. Thank you and best regards, Dave.

Version 2.1 (dev): https://github.com/FlipZoomMedia/ProcessWire-AIOM-All-In-One-Minify/tree/dev

**Comment by smdnetau** [comment]
Hi David,

That appears to be working for me now. Thanks!
